In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = sns.load_dataset("iris")

In [3]:
#X is feature vectors
X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]

# y is labels
Y = df[['species']]

In [4]:
from sklearn.preprocessing import StandardScaler

X_scaled = StandardScaler().fit_transform(X)

In [5]:
features =X.T  # X 데이터는 150 × 4 이라면,
               # feature 는 4 × 150 이다.

covariance_matrix = np.cov(features)
print(covariance_matrix)

[[ 0.68569351 -0.042434    1.27431544  0.51627069]
 [-0.042434    0.18997942 -0.32965638 -0.12163937]
 [ 1.27431544 -0.32965638  3.11627785  1.2956094 ]
 [ 0.51627069 -0.12163937  1.2956094   0.58100626]]


In [6]:
values, vectors = np.linalg.eig(covariance_matrix)

print('\nEigenvalues \n%s '% values[:])
print('\nEigenvectros \n%s'  %  vectors[:])


Eigenvalues 
[4.22824171 0.24267075 0.0782095  0.02383509] 

Eigenvectros 
[[ 0.36138659 -0.65658877 -0.58202985  0.31548719]
 [-0.08452251 -0.73016143  0.59791083 -0.3197231 ]
 [ 0.85667061  0.17337266  0.07623608 -0.47983899]
 [ 0.3582892   0.07548102  0.54583143  0.75365743]]


In [11]:
(values[0]+values[1])/values.sum()

0.9776852063187949

In [13]:
u1 = values[0] * vectors[0]